# Each letter represents a colour marker:
#   k, r, g, y, b, m, c, w, d
# which stands for:
#   blacK, Red, Green, Yellow, Blue, Magenta, Cyan, White, Default
# Capital letters represent bold
# Copy to ~/.bpython/foo.theme and set "color_scheme = foo" in ~/bpython/config
[syntax]
keyword = G
name = w
comment = g
string = y
error = R
number = B
operator = W
punctuation = W
token = C
paren = C

[interface]
background = d
output = d
main = d
prompt = g
prompt_more = r