#!/usr/bin/env python3

import sys
import argparse
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument(
    "-f",
    "--full",
    action="store_true",
    help="print full version",
)

def main():
    res = subprocess.run(['go', 'version'], stdout=subprocess.PIPE)
    raw = res.stdout.decode('utf8').split()
    if len(raw) != 4:
        print('[-] unknown format: ', raw)
        return 1

    ver = raw[2].strip('go')
    arg = parser.parse_args()

    if not arg.full:
        ver = ver[:ver.rindex('.')]

    print(ver)
    return 0


sys.exit(main())

#vim:ft=py3
