#!/usr/bin/env python3

import subprocess
import sys


def main():
    res = subprocess.run(['go', 'version'], stdout=subprocess.PIPE)
    raw = res.stdout.decode('utf8').split()
    if len(raw) != 4:
        print('[-] unknown format: ', raw)
        return 1

    ver = raw[2].strip('go')
    print(ver)

    return 0


sys.exit(main())

#vim:ft=py3
