#!/bin/bash

# pause all notifies
dunstctl set-paused true

# set en layout
dbus-send --dest=ru.gentoo.KbddService /ru/gentoo/KbddService ru.gentoo.kbdd.set_layout uint32:0

# lock
i3lock --nofork --ignore-empty-password --image="$(cat "${HOME}"/.cache/wal/wal)"

# un-pause notifies
dunstctl set-paused false
