#!/bin/bash
#
# start or show cmus scratchpad.

cmus="cmus"

show() { i3-msg "[instance=\"^cmus$\"] scratchpad show"; }

if pgrep -x "$cmus" >/dev/null; then
    show
else
    kitty --name "$cmus" "$cmus" &
    sleep 0.5
    show
fi

#vim:ft=bash
