#!/usr/bin/env python3
#
# print all current assigned ip4 addrs.
#

import sys
import socket
from ipaddress import IPv4Network

import psutil


def get_ip4(name, addrs):
    for a in addrs.get(name, []):
        if a.family != socket.AF_INET:
            continue
        if a.broadcast is None:
            continue
        yield (a.address, a.netmask, a.broadcast)


def print_net(iface, ip, prefix, mask, bcast):
    print(f"{iface}:")
    print(f"\tip:        {ip}")
    print(f"\tmask:      {mask} /{prefix}")
    print(f"\tbroadcast: {bcast}\n")


def main():
    ifaces = psutil.net_if_stats()
    iaddrs = psutil.net_if_addrs()

    print("")

    for iface, stat in ifaces.items():
        if not stat.isup:
            continue
        for addr, mask, bcast in get_ip4(iface, iaddrs):
            prefix = IPv4Network((0, mask)).prefixlen
            print_net(iface, addr, prefix, mask, bcast)

    return 0


sys.exit(main())

#vim:ft=py3
