#!/usr/bin/env python3
# source: https://github.com/s0rg/dotfiles
#
# returns random user-agent string
#

import os
import sys
from random import choice

# list taken from: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
ua_src = os.path.join(os.environ["XDG_DATA_HOME"], "rand_ua.list")


def main():
    with open(ua_src, 'rt', encoding='utf8') as fd:
        l = fd.readlines()
        print(choice(l).strip(), end='')

    return 0


sys.exit(main())

#vim:ft=py3
