#!/usr/bin/env python3
#

import os
import sys
from random import choice

# list taken from: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/


def main():
    uas = os.path.join(os.environ["XDG_DATA_HOME"], "rand_ua.list")
    with open(uas, 'rt', encoding='utf8') as fd:
        l = fd.readlines()
        print(choice(l).strip(), end='')

    return 0


sys.exit(main())

#vim:ft=py3
