#!/usr/bin/env python3

import math
from datetime import timedelta

import rofi_menu

actions = [
    {
        "icon": "\uF023",
        "name": "lock",
        "command": "i3-betterlock",
        "confirm": False
    },
    {
        "icon": "\u23FE",
        "name": "hibernate",
        "command": "systemctl hibernate",
        "confirm": True
    },
    {
        "icon": "\uF01E",
        "name": "reboot",
        "command": "systemctl reboot",
        "confirm": True
    },
    {
        "icon": "\uF011",
        "name": "poweroff",
        "command": "systemctl poweroff",
        "confirm": True
    },
]


def _get_uptime():
    with open("/proc/uptime", "r") as fd:
        seconds = float(fd.readline().split(maxsplit=1)[0])
        seconds = math.floor(seconds)

    return timedelta(seconds=seconds)


def _make_confirm_entry(action):
    confirm = "yes, <b>{name}</b>".format(**action)
    return rofi_menu.Menu(prompt="sure?",
                          items=[
                              rofi_menu.ShellItem("\uF00C " + confirm,
                                                  action["command"]),
                              rofi_menu.ExitItem("\uF00D no, cancel"),
                          ])


def _make_action_entry(action):
    title = "{icon} {name}".format(**action)

    if not action["confirm"]:
        return rofi_menu.ShellItem(title, action["command"])

    return rofi_menu.NestedMenu(
        title,
        _make_confirm_entry(action),
    )


def _make_menu():
    up = _get_uptime()

    return rofi_menu.Menu(
        prompt=f"uptime {up} ",
        items=[_make_action_entry(a) for a in actions],
    )


if __name__ == "__main__":
    rofi_menu.run(_make_menu())
