#!/bin/bash

BLANK=$(xset q | grep 'timeout:' | awk '{print $2}')
MSG_ID=1013

notify() {
	notify-send -a screen -r ${MSG_ID} -u low "blank" "state: ${1}"
}

if [[ "${BLANK}" == "0" ]]; then
	xset dpms
	xset s on
	notify "ON"
else
	xset -dpms
	xset s off
	notify "OFF"
fi

#vi: ft=bash
