#!/usr/bin/env python3
#
# toggles touchpad on/off, with notify
#

import sys
import subprocess as sh

import notify

PAD_NEEDLE = "touchpad"
XINPUT_BIN = "xinput"
XINPUT_PROP = "Device Enabled"
MSG_ID = 1010


def notify_state(msg):
    notify.send(PAD_NEEDLE, "state", msg, msg_id=MSG_ID)


def get_pad_name(needle=PAD_NEEDLE):
    p = sh.Popen([XINPUT_BIN, "list", "--name-only"], stdout=sh.PIPE)
    l = p.communicate()[0].decode().split("\n")
    r = list(filter(lambda s: needle in s.lower(), l))
    return r[0] if r else None


def get_pad_state(name):
    p = sh.Popen([XINPUT_BIN, "--list-props", name], stdout=sh.PIPE)
    l = p.communicate()[0].decode().split("\n")
    r = list(filter(lambda s: XINPUT_PROP in s, l))
    if len(r) < 1 or ":" not in r[0]:
        return False
    v = r[0].split(":")[1].strip()
    return v == "1"


def main():
    pad = get_pad_name()
    if pad is None:
        print("[-] no touchpad detected!", file=sys.stderr)
        return 1

    v, m = (False, "disabled") if get_pad_state(pad) else (True, "enabled")
    sh.Popen([XINPUT_BIN, "--enable" if v else "--disable", pad])
    notify_state(m)
    return 0


if __name__ == '__main__':
    sys.exit(main())

#vim:ft=py3
