#!/usr/bin/env python3
# source: https://github.com/s0rg/dotfiles
#
# the missing url encoder/decoder
#

import argparse
import sys
import urllib.parse as urlp

parser = argparse.ArgumentParser(description="url(en/de)coder")
parser.add_argument(
    "-d",
    "--decode",
    action="store_true",
    help="decode input",
)
parser.add_argument(
    "-l",
    "--legacy",
    action="store_true",
    help="use '%20' instead of '+' to encode spaces",
)
parser.add_argument(
    "input",
    nargs='?',
    help="input string to (en/de)code",
)


def quote(val, legacy):
    if legacy:
        return urlp.quote(val)
    return urlp.quote_plus(val)


def unquote(val, legacy):
    if legacy:
        return urlp.unquote(val)
    return urlp.unquote_plus(val)


def main():
    args = parser.parse_args()

    val = args.input
    if val is None:
        val = sys.stdin.read().strip()

    if args.decode:
        res = unquote(val, args.legacy)
    else:
        res = quote(val, args.legacy)

    print(res)

    return 0


if __name__ == '__main__':
    sys.exit(main())

#vim:ft=py3
