#!/bin/bash
# source: https://github.com/s0rg/dotfiles
#
# this script convert given video to webm with constant quality
#

IN=${1}
if [ -z "${IN}" ]; then
    echo "USAGE: ${0} <video> <quality:[0-63], default: 33>"
    exit 1
fi

OUT="${IN%%.*}".webm
CRF="${2:-33}"
START=$(date +'%s')

ffmpeg -hide_banner -i "${IN}" -crf "${CRF}" -pass 1 \
    -c:v libvpx-vp9 -b:v 0 \
    -f null /dev/null || exit 1

ffmpeg -hide_banner -i "${IN}" -crf "${CRF}" -pass 2 \
    -c:v libvpx-vp9 -b:v 0 -c:a libopus -b:a 64k \
    -f webm "${OUT}" || exit 1

rm ffmpeg2pass-0.log

SEC="$(($(date +'%s') - START))"

echo "OLD : $(du -sh "${IN}")"
echo "NEW : $(du -sh "${OUT}")"
echo "TIME: $(((SEC / 60) % 60))m $((SEC % 60))s"

exit 0

#vi:ft=bash
