#!/bin/bash
#
# this scripts runs over plugins in $HOME/.vim/bundle dir, if no file name given,
# if so, it only updates all plugins in your bundle (git-pull'ing them), with file,
# it also install (git clone) all missing plugins.

ROOT=$HOME/.vim/bundle

if [[ $# == 0 ]]; then
    ITEMS=$(ls -1 "$ROOT")
else
    ITEMS=$(cat "$1")
fi

for p in $ITEMS; do
    n=$(basename "$p")
    [[ "${n##*.}" == "git" ]] && n="${n%.*}" # cut-off '.git' suffix

    if [[ -d $ROOT/$n ]]; then
        echo "updating: $n..."
        git -C "$ROOT/$n" pull
    else
        echo "installing: $n..."
        git -C "$ROOT" clone "$p"
    fi
    echo
done

#vim:ft=bash
