#!/bin/bash
# source: https://github.com/s0rg/dotfiles
#
# this script runs over plugins in $HOME/.vim/bundle dir
# and prints their remote repos uris.
#

ROOT=$HOME/.vim/bundle
ITEMS=$(ls -1 "$ROOT")

for p in $ITEMS; do
    git -C "$ROOT/$p" remote get-url origin
done

#vim:ft=bash
