#!/bin/bash
#
# this script starts zoom meeting, from clipboard url or first argument.

xcmd='xclip -selection clipboard -target STRING'
xget="$xcmd -out"
xset="$xcmd -in"

if [[ $# == 0 ]]; then
    link="$($xget)"
    echo -n '' | $xset
else
    link="$1"
fi

echo "starting zoom for: $link"
xdg-open "$(make_zoom_url "$link")"

#vi:ft=bash
